version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/infra/shared/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/infra/platform/"
    schedule:
      interval: "weekly"