name: Shared Configuration Deployment

on:
  push:
    branches: [ main ]
    paths:
      - 'configurations/shared/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'configurations/shared/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  deploy:
    name: Deploy Shared Configurations
    uses: ./.github/workflows/config-template.yml
    secrets: inherit
    with:
      componentName: "shared"
      environments: |
        [
          { "environment": "Development", "region": "westeurope" },
          { "environment": "QA", "region": "westeurope" }
        ]
